app/code/blogproject/blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='top'),
    path('post', views.BlogPostView.as_view(), name='post'),
    path('delete/<int:pk>', views.BlogDeleteView.as_view(), name='delete'),
    path('update/<int:pk>', views.BlogUpdateView.as_view(), name='update'),
    path('detail/<int:pk>', views.BlogDetailView.as_view(), name='detail'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

]

app/code/blogproject/blogproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogapp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/code/blogproject/blogapp/models.py
from django.db import models
from datetime import datetime
# Create your models here.

class Book(models.Model):
    title = models.CharField(verbose_name="タイトル",max_length=200)
    text = models.TextField(verbose_name="本文",max_length=500)
    date = models.DateField(verbose_name="日付",default=datetime.now)
    image = models.ImageField(verbose_name="本のイメージ",upload_to='img/')

    def __str__(self):
        return self.title

app/code/blogproject/blogapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import Book
from .Form import BookForm
from django.views.generic import TemplateView,ListView,FormView,CreateView,DeleteView,DetailView,UpdateView
from django.contrib.auth.views import (LoginView,LogoutView)
from django.contrib.auth.mixins import LoginRequiredMixin
from .Form import LoginForm
import datetime

class Login(LoginView):
    form_class = LoginForm
    template_name = "blogproject/login.html"


class Logout(LogoutView):
    template_name = "blogproject/login.html"


# Create your views here.
class BlogTopView(TemplateView):
    template_name = "blogproject/top.html"

class BlogListView(ListView):
    paginate_by = 5
    template_name = "blogproject/list.html"
    queryset = Book.objects.all()


    def trancerate_date(self,model):
        setattr(model, 'date', model.date.strftime('%Y年/%m月/%d日'))
        return model


    def get_context_data(self, *, object_list=None, **kwargs):


        """Get the context for this view."""
        queryset = object_list if object_list is not None else self.object_list
        page_size = self.get_paginate_by(queryset)
        context_object_name = self.get_context_object_name(queryset)
        queryset = list(map(self.trancerate_date, queryset))

        if page_size:
            paginator, page, queryset, is_paginated = self.paginate_queryset(queryset, page_size)

            if page.number -5 <=1:
                prev = [i for i in range(2,page.number)]
            else:
                prev = [i for i in range(page.number -5,page.number)]

            if page.number +5>=page.paginator.num_pages:
                nextpage = [i for i in range(page.number+1,page.paginator.num_pages)]
            else:
                nextpage = [i for i in range(page.number +1,page.number +6)]


            context = {
                'paginator': paginator,
                'prev':prev,
                'page_obj': page,
                'next':nextpage,
                'is_paginated': is_paginated,
                'object_list': queryset
            }
        else:
            context = {
                'paginator': None,
                'page_obj': None,
                'is_paginated': False,
                'object_list': queryset
            }
        if context_object_name is not None:
            context[context_object_name] = queryset
        context.update(kwargs)
        return context

class BlogPostView(CreateView):
    template_name = "blogproject/post.html"
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('blog:top')

class BlogDeleteView(DeleteView):
    template_name = "blogproject/delete.html"
    model = Book
    success_url = reverse_lazy('blog:top')

class BlogDetailView(DetailView):
    template_name = "blogproject/detail.html"
    model = Book

class BlogUpdateView(UpdateView):
    template_name = "blogproject/update.html"
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('blog:top')

app/code/blogproject/templates/blogproject/delete.html
<!DOCTYPE html>
<html>

<head>
    <title>削除画面</title>
</head>

<body>
    <h1>削除ページ</h1>
    <form method="post">
        {{ object.title}}
        {{ post.text | linebreaksbr}}
        <p>こちらを削除します。</p>
        <button type="submit">削除する</button>
        {% csrf_token %}
    </form>

</body>

</html>

app/code/blogproject/templates/blogproject/detail.html
<!DOCTYPE html>
<html>

<head>
    <title>詳細画面</title>
</head>

<body>
    <h1>{{ object.title }}</h1>
    <img src="{{ object.image.url }}">

    <p>
        {{ object.text }}
    </p>


    <a href="{% url 'blog:update' object.pk %}">編集</a>



    <a href="{% url 'blog:delete' object.pk %}">削除</a>



    <a href="{% url 'blog:top' %}">bookリストに戻る</a>
</body>

</html>

app/code/blogproject/templates/blogproject/list.html
<!DOCTYPE html>
{% load static %}

<html>

<head>
    <title>bookフォルダー</title>
    <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css">
</head>

<body>
    <main>
        <h2>bookフォルダー</h2>

        <div class="table-wrapper">
            <table class="table">
                <thead>
                    <tr class="table-tr">
                        <th>本のタイトル</th>
                        <th>本の感想</th>
                        <th>作成日</th>
                    </tr>

                </thead>
                <tbody>
                    {% for obj in object_list %}

                    <tr class="table-td">
                        <td>
                            <a href="{% url 'blog:detail' obj.pk %}">

                                {{ obj.title}}
                            </a>
                        </td>

                        <td>
                            {{ obj.text}}
                        </td>
                        <td>
                            {{ obj.date}}
                        </td>

                    </tr>

                    {% endfor %}
                </tbody>

            </table>


            <div class="pagination">
                <span class="step-links">

                    {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; 最初へ</a>
                    {% for prev_obj in prev %}
                    <a href="?page={{ prev_obj }}">{{ prev_obj }}</a>
                    {% endfor %}


                    {% endif %}

                    <span class="current-page">{{ page_obj.number }}</span>

                    {% if page_obj.has_next %}
                    {% for next_obj in next %}
                    <a href="?page={{ next_obj }}">{{ next_obj }}</a>
                    {% endfor %}

                    <a href="?page={{ page_obj.paginator.num_pages }}">最後へ &raquo;</a>
                    {% endif %}
                </span>
            </div>
            <div class="btn post">
                <a href="{% url 'blog:post' %}">本を投稿する</a>

            </div>

        </div>

    </main>
</body>

</html>

app/code/blogproject/templates/blogproject/login.html
<!DOCTYPE html>

<html>

<head>
    <title>login画面</title>
</head>

<body>

    <h1>loginページ</h1>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">送信</button>
    </form>

    <!-- <a href="{% url 'blog:list' %}">詳細ページ</a> -->
</body>

</html>

app/code/blogproject/templates/blogproject/post.html
<!DOCTYPE html>
<html>

<head>
    <title>post画面</title>
</head>

<body>

    <h1>postページ</h1>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">送信</button>
    </form>

    <a href="{% url 'blog:top' %}">book一覧に戻る</a>
</body>

</html>

app/code/blogproject/templates/blogproject/top.html
<!DOCTYPE html>
<html>

<head>
    <title>詳細画面</title>
</head>

<body>
    <h1>トップページ</h1>
    <a href="{% url 'blog:list' %}">詳細ページ</a>
    <a href="{% url 'blog:post' %}">postページ</a>
</body>

</html>

app/code/blogproject/templates/blogproject/update.html
<!DOCTYPE html>
<html>

<head>
    <title>update画面</title>
</head>

<body>

    <h1>updateページ</h1>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">送信</button>
    </form>

    <a href="{% url 'blog:detail' object.pk%}">戻る</a>
</body>

</html>